### PR TITLE
Add pyramid data augmentation which mentioned in SE-SSD

### PR DESCRIPTION
**Pull request by OuyangJunyuan**
I modifiy the pyramid aug in SE-SSD official code released to fit OpenPCDet, and achieve performance improvement,
image

```yaml
- NAME: random_local_pyramid_aug
  DROP_PROB: 0.25
  SPARSIFY_PROB: 0.05
  SPARSIFY_MAX_NUM: 50
  SWAP_PROB: 0.1
  SWAP_MAX_NUM: 50
```
I test it with pointpillar as baseline in kitti dataset. result show that improvement consistent with what is mentioned in the [paper](https://openaccess.thecvf.com/content/CVPR2021/html/Zheng_SE-SSD_Self-Ensembling_Single-Stage_Object_Detector_From_Point_Cloud_CVPR_2021_paper.html) 
| model                   | Car AP@0.70, 0.70, 0.70   |
| ----------------------- | ------------------------- |
| pointpillar             | 86.4617, 77.2839, 74.6530 |
| pointpillar_pyramid_aug | 87.3165, 77.6379, 76.1656 |
| improvement             | 0.8548 ↑, 0.354 ↑, 1.5126 ↑    |

image

### CODE REVIEW

**Comment by vehxianfish** [comment]
Hi, thanks for your wonderful job. Do I only copy ` random_local_pyramid_aug ` to YAML file. And I do not join it when I make KITTI dataset? In other words. I only copy ` random_local_pyramid_aug ` to YAML file. And I do not make KITTI dataset from scratch

**Comment by OuyangJunyuan** [comment]
> 

yeah, and cp `random_local_pyramid_aug` in cfg to your own YAML file is all your need

**Comment by iloveai8086** [comment]
Hello, thank you for your work.When i am training with this YAML file, the occupation of GPU memory seems to have increased. Have you encountered this phenomenon when using it?

**Comment by vehxianfish** [comment]
> > 
> 
> yeah, and cp `random_local_pyramid_aug` in cfg to your own YAML file is all your need

Thanks, best wishes!

**Comment by sxq2100** [comment]
My val result id not well as the showed,mod is only 75.45,could you tell me what caused this result.

**Comment by ferrari700** [comment]
> yeah, and cp `random_local_pyramid_aug` in cfg to your own YAML file is all your need

If I am using pcdet version 0.3.0, how do I need to modify to achieve this?

**Comment by MartinHahner** [comment]
Here is an example how you can change [pv_rcnn.yaml](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/kitti_models/pv_rcnn.yaml) for the *KITTI* dataset:

```yaml
CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']

DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/kitti_dataset.yaml

    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: [ 'random_local_scaling', 'random_world_frustum_dropout', 'random_local_frustum_dropout' ]
        AUG_CONFIG_LIST:

            - NAME: random_local_pyramid_aug
              DROP_PROB: 0.25
              SPARSIFY_PROB: 0.05
              SPARSIFY_MAX_NUM: 50
              SWAP_PROB: 0.1
              SWAP_MAX_NUM: 50

            ##########
            # global #
            ##########

            - NAME: random_world_translation
              NOISE_TRANSLATE_STD: 0.2
              ALONG_AXIS_LIST: [ 'x', 'y', 'z' ]

            - NAME: random_world_rotation
              WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]        # [-π/4, π/4]

            - NAME: random_world_scaling
              WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

            - NAME: random_world_flip
              ALONG_AXIS_LIST: [ 'x' ]

            #########
            # local #
            #########

            - NAME: random_local_rotation
              LOCAL_ROT_ANGLE: [ -0.15707963267, 0.15707963267 ]  # [-π/20, π/20]

            - NAME: random_world_translation
              NOISE_TRANSLATE_STD: 0.25
              ALONG_AXIS_LIST: [ 'x', 'y', 'z' ]

            ######
            # GT #
            ######

            - NAME: gt_sampling
              USE_ROAD_PLANE: True
              DB_INFO_PATH:
                  - kitti_dbinfos_train.pkl
              PREPARE: {
                  filter_by_min_points: [ 'Car:5', 'Pedestrian:5', 'Cyclist:5' ],
                  filter_by_difficulty: [ -1 ],  # -1=unknown, 0=easy, 1=moderate, 2=hard
              }
              SAMPLE_GROUPS: [ 'Car:15','Pedestrian:15', 'Cyclist:15' ]
              NUM_POINT_FEATURES: 4
              DATABASE_WITH_FAKELIDAR: False
              REMOVE_EXTRA_WIDTH: [ 0.0, 0.0, 0.0 ]
              LIMIT_WHOLE_SCENE: False

              SPARSE_SAMPLES:
                  ADD_SPARSE_SAMPLES: False
                  FILTER_BY_MIN_POINTS: [ 'Car:0', 'Pedestrian:200', 'Cyclist:200' ]
                  POINT_CLOUD_RANGE: [ 20., 70. ]
                  PROBABILITY: 0.4
                  HEIGHT: 64
                  WIDTH: 512
                  SLICES: 2

MODEL:
    NAME: PVRCNN

    VFE:
        NAME: MeanVFE

    BACKBONE_3D:
        NAME: VoxelBackBone8x

    MAP_TO_BEV:
        NAME: HeightCompression
        NUM_BEV_FEATURES: 256

    BACKBONE_2D:
        NAME: BaseBEVBackbone

        LAYER_NUMS: [5, 5]
        LAYER_STRIDES: [1, 2]
        NUM_FILTERS: [128, 256]
        UPSAMPLE_STRIDES: [1, 2]
        NUM_UPSAMPLE_FILTERS: [256, 256]

    DENSE_HEAD:
        NAME: AnchorHeadSingle
        CLASS_AGNOSTIC: False

        USE_DIRECTION_CLASSIFIER: True
        DIR_OFFSET: 0.78539
        DIR_LIMIT_OFFSET: 0.0
        NUM_DIR_BINS: 2

        ANCHOR_GENERATOR_CONFIG: [
            {
                'class_name': 'Car',
                'anchor_sizes': [[3.9, 1.6, 1.56]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-1.78],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.6,
                'unmatched_threshold': 0.45
            },
            {
                'class_name': 'Pedestrian',
                'anchor_sizes': [[0.8, 0.6, 1.73]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-0.6],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35
            },
            {
                'class_name': 'Cyclist',
                'anchor_sizes': [[1.76, 0.6, 1.73]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [-0.6],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.5,
                'unmatched_threshold': 0.35
            }
        ]

        TARGET_ASSIGNER_CONFIG:
            NAME: AxisAlignedTargetAssigner
            POS_FRACTION: -1.0
            SAMPLE_SIZE: 512
            NORM_BY_NUM_EXAMPLES: False
            MATCH_HEIGHT: False
            BOX_CODER: ResidualCoder

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 2.0,
                'dir_weight': 0.2,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    PFE:
        NAME: VoxelSetAbstraction
        POINT_SOURCE: raw_points
        NUM_KEYPOINTS: 2048
        NUM_OUTPUT_FEATURES: 128
        SAMPLE_METHOD: FPS

        FEATURES_SOURCE: ['bev', 'x_conv1', 'x_conv2', 'x_conv3', 'x_conv4', 'raw_points']
        SA_LAYER:
            raw_points:
                MLPS: [[16, 16], [16, 16]]
                POOL_RADIUS: [0.4, 0.8]
                NSAMPLE: [16, 16]
            x_conv1:
                DOWNSAMPLE_FACTOR: 1
                MLPS: [[16, 16], [16, 16]]
                POOL_RADIUS: [0.4, 0.8]
                NSAMPLE: [16, 16]
            x_conv2:
                DOWNSAMPLE_FACTOR: 2
                MLPS: [[32, 32], [32, 32]]
                POOL_RADIUS: [0.8, 1.2]
                NSAMPLE: [16, 32]
            x_conv3:
                DOWNSAMPLE_FACTOR: 4
                MLPS: [[64, 64], [64, 64]]
                POOL_RADIUS: [1.2, 2.4]
                NSAMPLE: [16, 32]
            x_conv4:
                DOWNSAMPLE_FACTOR: 8
                MLPS: [[64, 64], [64, 64]]
                POOL_RADIUS: [2.4, 4.8]
                NSAMPLE: [16, 32]

    POINT_HEAD:
        NAME: PointHeadSimple
        CLS_FC: [256, 256]
        CLASS_AGNOSTIC: True
        USE_POINT_FEATURES_BEFORE_FUSION: True
        TARGET_CONFIG:
            GT_EXTRA_WIDTH: [0.2, 0.2, 0.2]
        LOSS_CONFIG:
            LOSS_REG: smooth-l1
            LOSS_WEIGHTS: {
                'point_cls_weight': 1.0,
            }

    ROI_HEAD:
        NAME: PVRCNNHead
        CLASS_AGNOSTIC: True

        SHARED_FC: [256, 256]
        CLS_FC: [256, 256]
        REG_FC: [256, 256]
        DP_RATIO: 0.3

        NMS_CONFIG:
            TRAIN:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 9000
                NMS_POST_MAXSIZE: 512
                NMS_THRESH: 0.8
            TEST:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 1024
                NMS_POST_MAXSIZE: 100
                NMS_THRESH: 0.7

        ROI_GRID_POOL:
            GRID_SIZE: 6
            MLPS: [[64, 64], [64, 64]]
            POOL_RADIUS: [0.8, 1.6]
            NSAMPLE: [16, 16]
            POOL_METHOD: max_pool

        TARGET_CONFIG:
            BOX_CODER: ResidualCoder
            ROI_PER_IMAGE: 128
            FG_RATIO: 0.5

            SAMPLE_ROI_BY_EACH_CLASS: True
            CLS_SCORE_TYPE: roi_iou

            CLS_FG_THRESH: 0.75
            CLS_BG_THRESH: 0.25
            CLS_BG_THRESH_LO: 0.1
            HARD_BG_RATIO: 0.8

            REG_FG_THRESH: 0.55

        LOSS_CONFIG:
            CLS_LOSS: BinaryCrossEntropy
            REG_LOSS: smooth-l1
            CORNER_LOSS_REGULARIZATION: True
            LOSS_WEIGHTS: {
                'rcnn_cls_weight': 1.0,
                'rcnn_reg_weight': 1.0,
                'rcnn_corner_weight': 1.0,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.1
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 2
    NUM_EPOCHS: 80

    OPTIMIZER: adam_onecycle
    LR: 0.01
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10

```

**Comment by ferrari700** [comment]
But OPenPCDet 0.3.0 doesn't defined these methods (global_frustum_dropout_top, local_scaling, local_rotation, local_frustum_dropout_top, local_pyramid_dropout......) in pcdet.datasets.augmentor.augmentor_utils.py,
In this case, is it still effective to only modify yaml?

**Comment by MartinHahner** [comment]
I mean you have to of course include the code changes of this pull request, there is no way around that.

**Comment by ferrari700** [comment]
> I mean you have to of course include the code changes of this pull request, there is no way around that.
So I just need to replace augmentor_utils.py, no need to reinstall latest OPenPCdet, right?

**Comment by MartinHahner** [comment]
The clean way would be to [cherry pick](https://www.atlassian.com/git/tutorials/cherry-pick) [this commit](https://github.com/open-mmlab/OpenPCDet/commit/7f977ea3ab5638bb0e927fbdbc21f7693a71563a).
I think you can just run `git cherry-pick 7f977ea3ab5638bb0e927fbdbc21f7693a71563a` or use [gitkraken](https://www.gitkraken.com/), 
where you have a nice user interface.

> So I just need to replace augmentor_utils.py and data_augmentor.py, no need to reinstall the latest OPenPCdet, right?

This should also work when you made no changes to these files yourself.

**Comment by ferrari700** [comment]
OK, thanks a lot for your help!
I found that I did not use data augmentation in dataset.py when I was training a custom dataset, but I only modified the data augmentation in yaml and used the same hyperparameters for training, but still had different results during testing. may I know what is the reason? Thanks!

**Comment by MartinHahner** [comment]
What do you mean by "different results during testing"?
It is "normal" that the final performance fluctuates by 1-2% when you execute the exact same experiment multiple times.

**Comment by ferrari700** [comment]
I use the recorded bagfile to view the boundingbox displayed by the trained model

**Comment by MartinHahner** [comment]
Then the answer is yes, they will never be exactly the same.

**Comment by ferrari700** [comment]
what is the reason? Thanks!

**Pull request merged**
