### PR TITLE
Custom dataset support

### LINKED ISSUE #176: Own dataset
Hello is there any way to train on custom dataset from .las files? And make predictions from this files too?

### LINKED ISSUE #198: Train custom data (without 2D information?)
Hi,

If I want to train my datasets, before that, I was wondering is it possible to only label and mark the target bounding box and class without providing any 2D information, such as calibration of the camera, images, and 2D rectangle box on images as KITTI does? 

In short, may I only use these 3D data as input to train?

Thanks in advance.

### LINKED ISSUE #252: Evaluate own Dataset
Hello,
this repo works very good for me and I already build my own dataset in Kitti format and the labels. So where do I put my labels so I can see the score for test.py. I need to see the score between my labels and the predicted labels.

### LINKED ISSUE #253: Problems using custom data sets
I am trying to use my own Lidar data to test PV-RCNN instead of kitti data, I used similar kaggle annotations
However, I get an error when trying to run the code and the error message is as follows
```
File "***/OpenPCDet/pcdet/datasets/innovusion/innovusion_dataset.py", line 77, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "***/OpenPCDet/pcdet/datasets/dataset.py", line 124, in prepare_data
    'gt_boxes_mask': gt_boxes_mask
  File "***/OpenPCDet/pcdet/datasets/augmentor/data_augmentor.py", line 93, in forward
    data_dict = cur_augmentor(data_dict=data_dict)
  File "***/OpenPCDet/pcdet/datasets/augmentor/database_sampler.py", line 179, in __call__
    sampled_boxes = np.stack([x['box3d_lidar'] for x in sampled_dict], axis=0).astype(np.float32)
  File "<__array_function__ internals>", line 6, in stack
  File "***/anaconda3/envs/ml/lib/python3.7/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```
I located the code and found that it was related to data enhancement, in pcdet/datasets/augmentor/database_sampler.py
```
    def __call__(self, data_dict):
        """
        Args:
            data_dict:
                gt_boxes: (N, 7 + C) [x, y, z, dx, dy, dz, heading, ...]

        Returns:

        """
        gt_boxes = data_dict['gt_boxes']
        gt_names = data_dict['gt_names'].astype(str)
        existed_boxes = gt_boxes
        total_valid_sampled_dict = []
        for class_name, sample_group in self.sample_groups.items():
            if self.limit_whole_scene:
                num_gt = np.sum(class_name == gt_names)
                sample_group['sample_num'] = str(int(self.sample_class_num[class_name]) - num_gt)
            if int(sample_group['sample_num']) > 0:
                sampled_dict = self.sample_with_fixed_number(class_name, sample_group)  ### need help

                sampled_boxes = np.stack([x['box3d_lidar'] for x in sampled_dict], axis=0).astype(np.float32)

                if self.sampler_cfg.get('DATABASE_WITH_FAKELIDAR', False):
                    sampled_boxes = box_utils.boxes3d_kitti_fakelidar_to_lidar(sampled_boxes)

                iou1 = iou3d_nms_utils.boxes_bev_iou_cpu(sampled_boxes[:, 0:7], existed_boxes[:, 0:7])
                iou2 = iou3d_nms_utils.boxes_bev_iou_cpu(sampled_boxes[:, 0:7], sampled_boxes[:, 0:7])
                iou2[range(sampled_boxes.shape[0]), range(sampled_boxes.shape[0])] = 0
                iou1 = iou1 if iou1.shape[1] > 0 else iou2
                valid_mask = ((iou1.max(axis=1) + iou2.max(axis=1)) == 0).nonzero()[0]
                valid_sampled_dict = [sampled_dict[x] for x in valid_mask]
                valid_sampled_boxes = sampled_boxes[valid_mask]

                existed_boxes = np.concatenate((existed_boxes, valid_sampled_boxes), axis=0)
                total_valid_sampled_dict.extend(valid_sampled_dict)

        sampled_gt_boxes = existed_boxes[gt_boxes.shape[0]:, :]
        if total_valid_sampled_dict.__len__() > 0:
            data_dict = self.add_sampled_boxes_to_scene(data_dict, sampled_gt_boxes, total_valid_sampled_dict)

        data_dict.pop('gt_boxes_mask')
        return data_dict
```
Then the key function is sample_with_fixed_number(self, class_name, sample_group)
```
    def sample_with_fixed_number(self, class_name, sample_group):
        """
        Args:
            class_name:
            sample_group:
        Returns:

        """
        sample_num, pointer, indices = int(sample_group['sample_num']), sample_group['pointer'], sample_group['indices']
        if pointer >= len(self.db_infos[class_name]):
            indices = np.random.permutation(len(self.db_infos[class_name]))
            pointer = 0

        sampled_dict = [self.db_infos[class_name][idx] for idx in indices[pointer: pointer + sample_num]]
        pointer += sample_num
        sample_group['pointer'] = pointer
        sample_group['indices'] = indices
        return sampled_dict
```
Self.db_infos is used in the code, it is specified by sampler_cfg.DB_INFO_PATH, but my data dose not have it, so I am stuck here, what do I need to do to fix it, or is there a detailed explanation for me to understand this code
Note: My data annotation format
```
id confidence center_x center_y center_z width length height yaw class_name
```
thank you all

### LINKED ISSUE #323: 用自己的数据训练
请问如果只用自己的数据训练，除了需要准备Bin格式的文件，label等，还需要准备其他什么文件吗？

### LINKED ISSUE #439: Demo on Custom data set in kitti format?
custom_data
Hello,
@sshaoshuai  
Firstly, I would like to thank OpenPCDet developers for their great work in Lidar perception. 

I tried the demo on Kitti data set and it worked fine. But on my data set in Kitti format, the demo is not working, I mean no prediction and bounding boxes on the objects. 
I checked other issues in this repo like [this](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/DEMO.md), [this](https://github.com/open-mmlab/OpenPCDet/issues/176) and [this](https://github.com/open-mmlab/OpenPCDet/issues/253#issuecomment-675535776l), but I did not find solution to my problem. 

custom data will be loaded in kitti format(.bin) and can visualize in mayavi, but no prediction and bounding boxes on the objects. I also changed the Z values(z+1.6 m, optional according to Demo.md) and unified coordinates narratives and I checked the co-ordinates system in mayavi UI, still not solved.

I think demo has nothing to do with __get__item in kitti_dataset.py, since part of this code is not being executed at all, when I checked with print statement. 
What I understood from the code, I do not need to change anything in the code for demo on custom data apart from values in Z axis and unified co-ordinates system. Since data is directly feed into the model for prediction/evalution, custom data may be comply with model trained with kitti data set. 

Could anyone familiar with this help me out to solve this?
Here is the output of the demo

`/home/surendra/pcdet/OpenPCDet/pcdet/models/roi_heads/pvrcnn_head.py:135: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  dense_idx = faked_features.nonzero()  # (N, 3) [x_idx, y_idx, z_idx]
[{'pred_boxes': tensor([], device='cuda:0', size=(0, 7)), 'pred_scores': tensor([], device='cuda:0'), 'pred_labels': tensor([], device='cuda:0', dtype=torch.int64)}]
`

Thanks in advance

### LINKED ISSUE #528: Customized dataset
Is there a tutorial that one can follow to make a customized dataset? Thing like how to organize the data, in terms of points and labels and how to apply it?

### LINKED ISSUE #579: Used my own data, but it outputs no results
In the quick demo, I used a frame of point cloud I collected by myself, and its format is .bin. I use kitti_models/pv_rcnn.yaml, but there is no prediction result after input. How can I modify the cfg file to adapt to my own data.Look forward to your answer.

### LINKED ISSUE #691: Train on my own dataset
Hi, everyone. I want to train PV-RCNN on my own point cloud data.
I have converted the data to KITTI format, with .bin file and one-to-one .txt annotation file. However, there is an essential problem confused me that the object heading. 
In the case of my data, x-axis is forward, y is the left and z is up, and the orientation defines the angle between the object and x-axis. It is different from the KITTI setting, and how should I modify the code in the OpenPCDet project to promise the rotation consistently?
Any help would be appropriated a lot!

### LINKED ISSUE #709: my own dataset
Hi, everyone, there are some questions confused me, could you please give me some helps?
My own dataset is lidar-only file on roadside scene:
1. How do I modify the data config file and dataloader, such as based on kitti dataset. The direction of zero orientation is long the x-axis, but it increase in clockwise manner. And the orientation is presented as angle, not the radian. 
2. How to set the range of point cloud and anchor? I have calculate the height, width, length, x, y and z value for each category, but the 'anchor_bottom_height' parameter still confuses me.
Any helps would be appreciated a lot.

### LINKED ISSUE #727: Questions about training custom data sets
Hello, if I need to train a custom data set (only point cloud data), do I need to convert the coordinates of the 3D bounding box in the label's txt file to the camera coordinate system like kitti ? Thanks!

### LINKED ISSUE #768: how to convert coordinates with own data?
724706.21999979 5649433.59000015 275.16000366 0.0
724706.21999979 5649433.27000046 275.16000366 0.0
724706.21999979 5649432.88999939 275.19000244 0.0
724706.21999979 5649432.56999969 275.17999268 0.0
724706.23000002 5649432.22000122 275.23001099 0.0
724706.23000002 5649431.87999916 275.20999146 0.0

this is how my points look like, its x, y, z and intensity value, in .npy is like 
[[724706.21999979 5649433.59000015 275.16000366 0.0]
 [724706.21999979 5649433.27000046 275.16000366 0.0]
 [724706.21999979 5649432.88999939 275.19000244 0.0]
 ...
 [724706.21999979 5649432.56999969 275.17999268 0.0]
 [724706.23000002 5649432.22000122 275.23001099 0.0]
 [724706.23000002 5649431.87999916 275.20999146 0.0]]

is it good conversion?

_Originally posted by @kamillasak in https://github.com/open-mmlab/OpenPCDet/issues/176#issuecomment-669183390_

### LINKED ISSUE #771: Training using our own dataset
Good evening,
First I would like to thank you for this project, I had a query regarding training using our own dataset. I see that in Demo you have shown how to use our own dataset of point cloud and save to numpy format and test it on a pre-trained model, is there a way we can train using our own dataset, if so could you please guide me as to how to do it, 
Thanks for your help

### LINKED ISSUE #836: Inference on custom data
I trained a model using WOD. But when i use it for inference on data from my own lidar(128 channel), I get inaccurate/useless outputs. I basically take the raw PointCloud data, put intensity of points through tanh, then pass it to VFE. However when I pass WOD data to model (straight from WOD .tfrecords to Pointcloud using OpenPCdet [functions](https://github.com/open-mmlab/OpenPCDet/blob/a9c66fee5348dcfb5f73ccca71becc2871ce3a78/pcdet/datasets/waymo/waymo_utils.py#L64) then to model) model works perfect. Is this a data distribution mismatch issue or am i missing something WOD SDK or OpenPCDet does while converting from .tfrecord to np array points.

### LINKED ISSUE #860: Custom dataset training error.
keep calling __getitem__.
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 155, in prepare_data
    return self.__getitem__(new_index)
  File "/nas/lyp/code/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 441, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)   #################################
  File "/nas/lyp/code/tools/../pcdet/datasets/dataset.py", line 127, in prepare_data
    data_dict = self.data_augmentor.forward(
  File "/nas/lyp/code/tools/../pcdet/datasets/augmentor/data_augmentor.py", line 240, in forward
    data_dict = cur_augmentor(data_dict=data_dict)
  File "/nas/lyp/code/tools/../pcdet/datasets/augmentor/data_augmentor.py", line 49, in random_world_flip
    gt_boxes, points = getattr(augmentor_utils, 'random_flip_along_%s' % cur_axis)(
  File "/nas/lyp/code/tools/../pcdet/datasets/augmentor/augmentor_utils.py", line 15, in random_flip_along_x
    enable = np.random.choice([False, True], replace=False, p=[0.5, 0.5])
  File "mtrand.pyx", line 978, in numpy.random.mtrand.RandomState.choice
  File "<__array_function__ internals>", line 5, in unique
  File "/root/anaconda3/envs/openpcdet/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 262, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/root/anaconda3/envs/openpcdet/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 315, in _unique1d
    ar = np.asanyarray(ar).flatten()
  File "/root/anaconda3/envs/openpcdet/lib/python3.8/site-packages/numpy/core/_asarray.py", line 171, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
RecursionError: maximum recursion depth exceeded while calling a Python object

### LINKED ISSUE #940: how  to train the pure lidar point dataset?
thanks for  your open project,  now  i  have only lidar point data, not image,calib  data.  can i use your  open project   to train my own dataset?   how to close the function of  calib,  image  parameters, using the only  lidar -point data

### LINKED ISSUE #945: train  custom dataset  ,occur this error
N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0

### LINKED ISSUE #953: training  custom data  error
RecursionError: maximum recursion depth exceeded while calling a Python object

### LINKED ISSUE #987: I need my custom_data training without 2d infos, also i dont want downgrade
<details><summary>pip env</summary>
<p>
absl-py                     0.15.0
addict                      2.4.0
anyio                       3.5.0
argon2-cffi                 21.3.0
argon2-cffi-bindings        21.2.0
asttokens                   2.0.5
astunparse                  1.6.3
attrs                       21.4.0
Babel                       2.10.1
backcall                    0.2.0
beautifulsoup4              4.11.1
black                       22.3.0
bleach                      5.0.0
cachetools                  5.0.0
ccimport                    0.3.7
certifi                     2021.10.8
cffi                        1.15.0
charset-normalizer          2.0.12
click                       8.1.3
colorama                    0.4.4
cumm                        0.2.8
cumm-cu113                  0.2.8
cycler                      0.11.0
Cython                      0.29.28
debugpy                     1.6.0
decorator                   5.1.1
defusedxml                  0.7.1
deprecation                 2.1.0
descartes                   1.1.0
dgl                         0.6.1
easydict                    1.9
entrypoints                 0.4
executing                   0.8.3
fastjsonschema              2.15.3
filelock                    3.6.0
fire                        0.4.0
flake8                      4.0.1
flatbuffers                 1.12
fonttools                   4.33.3
gast                        0.3.3
google-auth                 2.6.6
google-auth-oauthlib        0.4.6
google-pasta                0.2.0
grpcio                      1.32.0
h5py                        2.10.0
idna                        3.3
imageio                     2.19.0
importlib-metadata          4.11.3
importlib-resources         5.7.1
iniconfig                   1.1.1
ipykernel                   6.13.0
ipython                     8.3.0
ipython-genutils            0.2.0
ipywidgets                  7.7.0
jedi                        0.18.1
Jinja2                      3.1.2
joblib                      1.1.0
json5                       0.9.6
jsonschema                  4.4.0
jupyter                     1.0.0
jupyter-client              7.3.0
jupyter-console             6.4.3
jupyter-core                4.10.0
jupyter-packaging           0.12.0
jupyter-server              1.17.0
jupyterlab                  3.3.4
jupyterlab-pygments         0.2.2
jupyterlab-server           2.13.0
jupyterlab-widgets          1.1.0
keras-nightly               2.5.0.dev2021032900
Keras-Preprocessing         1.1.2
kiwisolver                  1.4.2
lark                        1.1.2
llvmlite                    0.36.0
lyft-dataset-sdk            0.0.8
Markdown                    3.3.6
MarkupSafe                  2.1.1
matplotlib                  3.5.1
matplotlib-inline           0.1.3
mccabe                      0.6.1
mistune                     0.8.4
mmcls                       0.23.0
mmcv-full                   1.5.0
mmdet                       2.24.1
mmdet3d                     1.0.0rc2            /data/test_model/mm/OpenPCDet/mmdetection3d
mmsegmentation              0.24.1
model-index                 0.1.11
mypy-extensions             0.4.3
nbclassic                   0.3.7
nbclient                    0.6.0
nbconvert                   6.5.0
nbformat                    5.3.0
nest-asyncio                1.5.5
networkx                    2.2
ninja                       1.10.2.3
nose                        1.3.7
notebook                    6.4.11
notebook-shim               0.1.0
numba                       0.53.0
numpy                       1.21.1
nuscenes-devkit             1.1.9
oauthlib                    3.2.0
olefile                     0.46
open3d                      0.15.2
opencv-python               4.5.5.64
opt-einsum                  3.3.0
ordered-set                 4.1.0
packaging                   21.3
pandas                      1.4.2
pandocfilters               1.5.0
parso                       0.8.3
pathspec                    0.9.0
pccm                        0.3.4
pcdet                       0.5.2+846cf3e       /data/test_model/mm/OpenPCDet
pexpect                     4.8.0
pickleshare                 0.7.5
Pillow                      9.1.0
pip                         21.2.4
platformdirs                2.5.2
plotly                      5.7.0
pluggy                      1.0.0
plyfile                     0.7.4
portalocker                 2.4.0
prettytable                 3.3.0
prometheus-client           0.14.1
prompt-toolkit              3.0.29
protobuf                    3.9.2
psutil                      5.9.0
ptyprocess                  0.7.0
pure-eval                   0.2.2
py                          1.11.0
pyasn1                      0.4.8
pyasn1-modules              0.2.8
pybind11                    2.9.2
pycocotools                 2.0.4
pycodestyle                 2.8.0
pycparser                   2.21
pyflakes                    2.4.0
Pygments                    2.12.0
pyparsing                   3.0.8
pypcd                       0.1.1
pyquaternion                0.9.9
pyrsistent                  0.18.1
pytest                      7.1.2
python-dateutil             2.8.2
python-lzf                  0.2.4
pytz                        2022.1
PyWavelets                  1.3.0
PyYAML                      6.0
pyzmq                       22.3.0
qtconsole                   5.3.0
QtPy                        2.1.0
requests                    2.27.1
requests-oauthlib           1.3.1
rsa                         4.8
scikit-image                0.19.2
scikit-learn                1.0.2
scipy                       1.8.0
Send2Trash                  1.8.0
setuptools                  61.2.0
Shapely                     1.8.2
SharedArray                 3.1.0
six                         1.15.0
sniffio                     1.2.0
soupsieve                   2.3.2.post1
spconv                      2.1.21
spconv-cu113                2.1.21
stack-data                  0.2.0
tabulate                    0.8.9
tenacity                    8.0.1
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
tensorboardX                2.5
tensorflow                  2.4.0
tensorflow-estimator        2.4.0
termcolor                   1.1.0
terminado                   0.13.3
terminaltables              3.1.10
threadpoolctl               3.1.0
tifffile                    2022.4.28
tinycss2                    1.1.1
tomli                       2.0.1
tomlkit                     0.10.2
torch                       1.9.1
torchaudio                  0.9.0
torchvision                 0.10.1
tornado                     6.1
tqdm                        4.64.0
traitlets                   5.1.1
trimesh                     2.35.39
typing_extensions           4.2.0
urllib3                     1.26.9
waymo-open-dataset-tf-2-4-0 1.4.1
wcwidth                     0.2.5
webencodings                0.5.1
websocket-client            1.3.2
Werkzeug                    2.1.2
wheel                       0.37.1
widgetsnbextension          3.6.0
wrapt                       1.12.1
yapf                        0.32.0
zipp                        3.8.0
</p>
</details>

I already installed every envs.

when i tried demo.py,
`Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main()
  File "demo.py", line 98, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/data/test_model/mm/OpenPCDet/pcdet/models/detectors/pv_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/usr/local/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/test_model/mm/OpenPCDet/pcdet/models/backbones_3d/pfe/voxel_set_abstraction.py", line 352, in forward
    keypoints = self.get_sampled_points(batch_dict)
  File "/data/test_model/mm/OpenPCDet/pcdet/models/backbones_3d/pfe/voxel_set_abstraction.py", line 254, in get_sampled_points
    cur_pt_idxs = pointnet2_stack_utils.farthest_point_sample(
  File "/data/test_model/mm/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/pointnet2_utils.py", line 180, in forward
    pointnet2.farthest_point_sampling_wrapper(B, N, npoint, xyz, temp, output)
AttributeError: module 'pcdet.ops.pointnet2.pointnet2_stack.pointnet2_stack_cuda' has no attribute 'farthest_point_sampling_wrapper'
`
IDK :(

Please you can help me.

And one more question
I want to train without 2d images, calibration, 2d label(2d infos)
i tried make own_datsets.py
but it doesnt work.

Any comments you can give me please.

Thk :)

### PR DESCRIPTION
**Pull request by OrangeSodahub**
Fix #771 Fix #987  Fix #953  Fix #945  Fix #940  Fix #860  Fix #836  Fix #768  Fix #727  Fix #709  Fix #691  Fix #579  Fix #528  Fix #439  Fix #323  Fix #253  Fix #252  Fix #198 Fix #176 
Many excellent 3D detection tools are released but not support the custom dataset. Especially for pure point cloud dataset - no images. This addition will help more to solve this. There are many tries or instructions on the Internet but most of them can't help exactly. I know there are a lot of users stuck in how to train there own dataset. Thanks to the convenience of OpenPCDet, it is not so difficult. So if add custom dataset support then it will be more practical.

### CODE REVIEW

**Comment by jihanyang** [comment]
Thanks for your nice PR! I will ask shaoshuai to co-review this PR with some modification to make this feature more comprehensive!

**Comment by d33dler** [comment]
would it be possible to train a Waymo model using this custom dataset creation?

**Comment by OrangeSodahub** [comment]
@d33dler  You mean using Waymo dataset? This PR is to train custom (unofficial) dataset, the official configuration of Waymo is already supported: https://github.com/open-mmlab/OpenPCDet#waymo-open-dataset-baselines
For pure pointcloud dataset (no images), this PR may help you.

**Comment by jihanyang** [comment]
@OrangeSodahub Hello, thanks for your work. As a large modification we want to make based on it, we modify it on my forked repo and create a new PR (I cannot push to your forked repo). Notice that all your commits are keep in that new PR (see #1072). I will close this comment. Feel free to raise a new PR if you have any other ideas.

**Comment by lijin123red** [comment]
hello,i notice there is "no evaluation" process in your fix that no AP value is generated in the train stage,so would you help to add the evaluation?

**Pull request closed without merging**
